### ISSUE TITLE
Run the code

### ISSUE THREAD

**Issue by rustik-9704** [dunbar12138/Audiovisual-Synthesis#9]
Hello!
Can anyone explain to a newbie how to run this code? I'm using pycharm. Sepcifically, they say: to run the code, we have to run this 
python train_audio.py --data_path PATH_TO_TRAINING_DATA --experiment_name EXPERIMENT_NAME --save_freq SAVE_FREQ --test_path_A PATH_TO_TEST_AUDIO --test_path_B PATH_TO_TEST_AUDIO --batch_size BATCH_SIZE --save_dir PATH_TO_SAVE_MODEL

What should I do to run it on my computer. What is each piece responsible for?

**Comment by rustik-9704** [comment]
Hello! Could you please help me figure out. When I run the code, I get the following error 
 C:\Users\student\PycharmProjects\Audiovisual-Synthesis>python train_audio.py --data_path C:\Users\student\Homework\project\p225_003.wav --experiment_name VC_e
xample_run --save_freq 2000 --test_path_A C:\Users\student\Homework\project\p226_005.wav --test_path_B C:\Users\student\Homework\project\p227_011.wav --batch_size 4
--save_dir C:\Users\student\Homework\project\save_models
2020-05-22 23:35:19.793865: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "train_audio.py", line 6, in <module>
    from data.Sample_dataset import MultiAudio
  File "C:\Users\student\PycharmProjects\Audiovisual-Synthesis\data\__init__.py", line 4, in <module>
    from audioUtils.hparams import hparams
  File "C:\Users\student\PycharmProjects\Audiovisual-Synthesis\audioUtils\hparams.py", line 1, in <module>
    from tensorflow.contrib.training import HParams
  File "C:\Users\student\Anaconda3\lib\site-packages\tensorflow\contrib\__init__.py", line 37, in <module>
    from tensorflow.contrib import cudnn_rnn
  File "C:\Users\student\Anaconda3\lib\site-packages\tensorflow\contrib\cudnn_rnn\__init__.py", line 38, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers import *
  File "C:\Users\student\Anaconda3\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\layers\__init__.py", line 23, in <module>
    from tensorflow.contrib.cudnn_rnn.python.layers.cudnn_rnn import *
  File "C:\Users\student\Anaconda3\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\layers\cudnn_rnn.py", line 20, in <module>
    from tensorflow.contrib.cudnn_rnn.python.ops import cudnn_rnn_ops
  File "C:\Users\student\Anaconda3\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\ops\cudnn_rnn_ops.py", line 22, in <module>
    from tensorflow.contrib.rnn.python.ops import lstm_ops
  File "C:\Users\student\Anaconda3\lib\site-packages\tensorflow\contrib\rnn\__init__.py", line 90, in <module>
    from tensorflow.contrib.rnn.python.ops.gru_ops import *
  File "C:\Users\student\Anaconda3\lib\site-packages\tensorflow\contrib\rnn\python\ops\gru_ops.py", line 20, in <module>
    from tensorflow.contrib.rnn.ops import gen_gru_ops
  File "C:\Users\student\Anaconda3\lib\site-packages\tensorflow\contrib\rnn\ops\gen_gru_ops.py", line 174, in <module>
    _ops.RegisterShape("GRUBlockCell")(None)
AttributeError: module 'tensorflow.python.framework.ops' has no attribute 'RegisterShape'
